theme = "sonokai_shusia"

[editor]
line-number = 'relative'
mouse = false
bufferline = "multiple"
scrolloff = 8
shell = ["sh", "-c"]

[editor.cursor-shape]
insert = 'bar'

[editor.statusline]
left = ['mode', 'spinner', 'file-name']
center = ['total-line-numbers', 'file-type']

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
